{% set name = "mdbook" %}
{% set version = "0.4.42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rust-lang/mdbook/archive/v{{ version }}.tar.gz
  sha256: cf1c7c293fd1ad3d51fe13cd385303df8b30004ba5edcc35dd8dbd23d670d528

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - mdbook --help

about:
  home: https://github.com/rust-lang/mdbook
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Create book from markdown files. Like Gitbook but implemented in Rust
  dev_url: https://github.com/rust-lang/mdbook

extra:
  recipe-maintainers:
    - danielnachun
