context:
  version: "0.5.0"

package:
  name: mdbook
  version: ${{ version }}

source:
  url: https://github.com/rust-lang/mdbook/archive/v${{ version }}.tar.gz
  sha256: 0d092a75ad1950e80f5f26529ebc10af25f8a795222224d72d9b99f259065575

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mdbook --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Create book from markdown files. Like Gitbook but implemented in Rust
  homepage: https://github.com/rust-lang/mdbook
  repository: https://github.com/rust-lang/mdbook

extra:
  recipe-maintainers:
    - danielnachun
