context:
  version: "0.4.44"

package:
  name: mdbook
  version: ${{ version }}

source:
  url: https://github.com/rust-lang/mdbook/archive/v${{ version }}.tar.gz
  sha256: af801a377aec2e671e6c6fe5ed3043c3e8cab674cbaa0a2faed36b8b6987ce10

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mdbook --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Create book from markdown files. Like Gitbook but implemented in Rust
  homepage: https://github.com/rust-lang/mdbook
  repository: https://github.com/rust-lang/mdbook

extra:
  recipe-maintainers:
    - danielnachun
